"""Add indexes and token expiration

Revision ID: 148256cf3931
Revises: c7a8e9f01234
Create Date: 2026-03-24 14:04:11.872046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '148256cf3931'
down_revision: Union[str, None] = 'c7a8e9f01234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chats_user', table_name='chats')
    op.create_index(op.f('ix_chats_user_id'), 'chats', ['user_id'], unique=False)
    op.drop_index('idx_chunks_content_tsv', table_name='document_chunks', postgresql_using='gin')
    op.drop_index('idx_chunks_document', table_name='document_chunks')
    op.drop_index('idx_chunks_user', table_name='document_chunks')
    op.create_index('idx_chunks_embedding', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_user_id'), 'document_chunks', ['user_id'], unique=False)
    op.drop_index('idx_documents_user', table_name='documents')
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.drop_index('idx_messages_chat', table_name='messages')
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    op.add_column('users', sa.Column('verification_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('users', 'verification_token_expires_at')
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.create_index('idx_messages_chat', 'messages', ['chat_id'], unique=False)
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.create_index('idx_documents_user', 'documents', ['user_id'], unique=False)
    op.drop_index(op.f('ix_document_chunks_user_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index('idx_chunks_embedding', table_name='document_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_chunks_user', 'document_chunks', ['user_id'], unique=False)
    op.create_index('idx_chunks_document', 'document_chunks', ['document_id'], unique=False)
    op.create_index('idx_chunks_content_tsv', 'document_chunks', ['content_tsv'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_chats_user_id'), table_name='chats')
    op.create_index('idx_chats_user', 'chats', ['user_id'], unique=False)
    # ### end Alembic commands ###
