"""add document metadata columns

Revision ID: 60fc8261209d
Revises: 181890b4dc8e
Create Date: 2026-03-03 06:26:25.633057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60fc8261209d'
down_revision: Union[str, None] = '181890b4dc8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('document_chunks_embedding_idx', table_name='document_chunks', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('title', sa.String(length=500), nullable=True))
    op.add_column('documents', sa.Column('author', sa.String(length=500), nullable=True))
    op.add_column('documents', sa.Column('year', sa.String(length=10), nullable=True))
    op.add_column('documents', sa.Column('journal', sa.String(length=500), nullable=True))
    op.add_column('documents', sa.Column('doi', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('abstract', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'error_message')
    op.drop_column('documents', 'abstract')
    op.drop_column('documents', 'doi')
    op.drop_column('documents', 'journal')
    op.drop_column('documents', 'year')
    op.drop_column('documents', 'author')
    op.drop_column('documents', 'title')
    op.drop_column('documents', 'file_size')
    op.create_index('document_chunks_embedding_idx', 'document_chunks', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###
